issues fixed
an issue popped up earlier two weeks ago and multiple users were affected because of a ytdl update. the developer came up with an update: https://github.com/fent/node-ytdl-core/pull/520/commits/dd1c93150e175e8e9bea4a6035348794181caf73

error: 

    throw err;
    ^
Error: Cannot find module 'm3u8stream/lib/parse-time'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/rbd/pnpm-volume/71b5ddd8-2a78-46fc-aba4-68049f14880d/node_modules/.registry.npmjs.org/ytdl-core/1.0.0/node_modules/ytdl-core/lib/info-extras.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

solution:

install packages m3u8stream and parse-time

code in main file:

const m3u8stream = require('m3u8stream');

const parseTime   = require('m3u8stream/dist/parse-time');